name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3  # Upgraded to v3 to use the latest Node.js version

      # Replaced set-output with environment files
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v3  # Upgraded to v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v3  # Upgraded to v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      # Reset Git config to avoid warnings
      - name: Remove extraheader from git config
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true

      # Use updated upload-artifact action
      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}




