name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Remove Git ExtraHeader
        run: git config --unset-all http.https://github.com/.extraheader

      - uses: actions/checkout@v3  # Updated to v3 for Node20

      # Cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v3  # Updated to v3 for Node20
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache local build directory
      - uses: actions/cache@v3  # Updated to v3 for Node20
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.date }}-

      # Build with Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android debug
          buildozer_version: stable

      # Upload artifacts using v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}



